# Generated by Django 4.2.7 on 2023-11-07 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_user_discordemail_user_stripeemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.CharField(default=uuid.uuid4, max_length=50, null=True, unique=True),
        ),
    ]
