# Generated by Django 4.2.7 on 2023-11-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_alter_user_usercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discordEmail',
        ),
        migrations.AddField(
            model_name='user',
            name='discordID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
